apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: yarivy/kafka-producer:latest
        imagePullPolicy: Always
        env:
          - name: KAFKA_BROKERS
            value: my-kafka.kafka.svc.cluster.local:9092